{
    "schema_version": "1.6.0",
    "id": "OESA-2023-1075",
    "modified": "2023-02-10T00:00:00Z",
    "published": "2023-02-10T00:00:00Z",
    "withdrawn": "",
    "aliases": null,
    "related": [
        "CVE-2022-47952"
    ],
    "summary": "lxc security update",
    "details": "Containers are insulated areas inside a system, which have their own namespace for filesystem, network, PID, IPC, CPU and memory allocation and which can be created using the Control Group and Namespace features included in the Linux kernel.\r\n\r\nSecurity Fix(es):\r\n\r\nlxc-user-nic in lxc through 5.0.1 is installed setuid root, and may allow local users to infer whether any file exists, even within a protected directory tree, because \u0026quot;Failed to open\u0026quot; often indicates that a file does not exist, whereas \u0026quot;does not refer to a network namespace path\u0026quot; often indicates that a file exists. NOTE: this is different from CVE-2018-6556 because the CVE-2018-6556 fix design was based on the premise that \u0026quot;we will report back to the user that the open() failed but the user has no way of knowing why it failed\u0026quot;; however, in many realistic cases, there are no plausible reasons for failing except that the file does not exist.(CVE-2022-47952)",
    "severity": null,
    "affected": [
        {
            "package": {
                "ecosystem": "openEuler-20.03-LTS-SP3",
                "name": "lxc",
                "purl": "pkg:rpm/lxc@4.0.3-2022102408.oe1"
            },
            "severity": null,
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "repo": "",
                    "events": [
                        {
                            "introduced": "0",
                            "fixed": "4.0.3-2022102408.oe1",
                            "last_affected": "",
                            "limit": ""
                        }
                    ],
                    "database_specific": null
                }
            ],
            "versions": null,
            "ecosystem_specific": {
                "aarch64": [
                    "lxc-4.0.3-2022102408.oe1.aarch64.rpm",
                    "lxc-debugsource-4.0.3-2022102408.oe1.aarch64.rpm",
                    "lxc-libs-4.0.3-2022102408.oe1.aarch64.rpm",
                    "lxc-debuginfo-4.0.3-2022102408.oe1.aarch64.rpm",
                    "lxc-devel-4.0.3-2022102408.oe1.aarch64.rpm"
                ],
                "noarch": [
                    "lxc-help-4.0.3-2022102408.oe1.noarch.rpm"
                ],
                "src": [
                    "lxc-4.0.3-2022102408.oe1.src.rpm"
                ],
                "x86_64": [
                    "lxc-devel-4.0.3-2022102408.oe1.x86_64.rpm",
                    "lxc-libs-4.0.3-2022102408.oe1.x86_64.rpm",
                    "lxc-4.0.3-2022102408.oe1.x86_64.rpm",
                    "lxc-debugsource-4.0.3-2022102408.oe1.x86_64.rpm",
                    "lxc-debuginfo-4.0.3-2022102408.oe1.x86_64.rpm"
                ]
            },
            "database_specific": null
        }
    ],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-47952"
        }
    ],
    "credits": null,
    "database_specific": {
        "severity": "Low"
    }
}