{
    "schema_version": "1.6.0",
    "id": "OESA-2023-1211",
    "modified": "2023-04-11T00:00:00Z",
    "published": "2023-04-11T00:00:00Z",
    "withdrawn": "",
    "aliases": null,
    "related": [
        "CVE-2023-28328",
        "CVE-2023-1380",
        "CVE-2023-1513",
        "CVE-2023-28772"
    ],
    "summary": "kernel security update",
    "details": "The Linux Kernel, the operating system core itself.\r\n\r\nSecurity Fix(es):\r\n\r\n\nKernel: A denial of service issue in  az6027 driver in\ndrivers/media/usb/dev-usb/az6027.c(CVE-2023-28328)\r\n\r\nA slab-out-of-bound read problem was found in brcmf_get_assoc_ies in drivers/net/wireless/broadcom/brcm80211/brcmfmac/cfg80211.c in the Linux Kernel. This issue could occur when assoc_info-\u0026gt;req_len data is bigger than the size of the buffer, defined as WL_EXTRA_BUF_MAX, leading to a denial of service.(CVE-2023-1380)\r\n\r\nA flaw was found in KVM. When calling the KVM_GET_DEBUGREGS ioctl, on 32-bit systems, there might be some uninitialized portions of the kvm_debugregs structure that could be copied to userspace, causing an information leak.(CVE-2023-1513)\n\nAn issue was discovered in the Linux kernel before 5.13.3. lib/seq_buf.c has a seq_buf_putmem_hex buffer overflow.(CVE-2023-28772)",
    "severity": null,
    "affected": [
        {
            "package": {
                "ecosystem": "openEuler-20.03-LTS-SP1",
                "name": "kernel",
                "purl": "pkg:rpm/kernel@4.19.90-2304.1.0.0196.oe1"
            },
            "severity": null,
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "repo": "",
                    "events": [
                        {
                            "introduced": "0",
                            "fixed": "4.19.90-2304.1.0.0196.oe1",
                            "last_affected": "",
                            "limit": ""
                        }
                    ],
                    "database_specific": null
                }
            ],
            "versions": null,
            "ecosystem_specific": {
                "aarch64": [
                    "kernel-debuginfo-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "python3-perf-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "kernel-tools-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "python2-perf-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "kernel-tools-devel-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "bpftool-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "python2-perf-debuginfo-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "kernel-tools-debuginfo-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "kernel-debugsource-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "bpftool-debuginfo-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "perf-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "perf-debuginfo-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "kernel-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "kernel-source-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "kernel-devel-4.19.90-2304.1.0.0196.oe1.aarch64.rpm",
                    "python3-perf-debuginfo-4.19.90-2304.1.0.0196.oe1.aarch64.rpm"
                ],
                "src": [
                    "kernel-4.19.90-2304.1.0.0196.oe1.src.rpm"
                ],
                "x86_64": [
                    "kernel-tools-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "kernel-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "bpftool-debuginfo-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "kernel-devel-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "kernel-tools-devel-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "python2-perf-debuginfo-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "bpftool-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "kernel-source-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "python2-perf-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "python3-perf-debuginfo-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "perf-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "perf-debuginfo-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "kernel-tools-debuginfo-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "kernel-debuginfo-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "python3-perf-4.19.90-2304.1.0.0196.oe1.x86_64.rpm",
                    "kernel-debugsource-4.19.90-2304.1.0.0196.oe1.x86_64.rpm"
                ]
            },
            "database_specific": null
        }
    ],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-28328"
        },
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-1380"
        },
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-1513"
        },
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-28772"
        }
    ],
    "credits": null,
    "database_specific": {
        "severity": "High"
    }
}