{
    "schema_version": "1.6.0",
    "id": "OESA-2023-1220",
    "modified": "2023-04-14T00:00:00Z",
    "published": "2023-04-14T00:00:00Z",
    "withdrawn": "",
    "aliases": null,
    "related": [
        "CVE-2023-0614"
    ],
    "summary": "libldb security update",
    "details": "An extensible library that implements an LDAP like API to access remote LDAP servers, or use local tdb databases.\r\n\r\nSecurity Fix(es):\r\n\r\nThe fix in 4.6.16, 4.7.9, 4.8.4 and 4.9.7 for CVE-2018-10919 Confidential attribute disclosure vi LDAP filters was insufficient and an attacker may be able to obtain confidential BitLocker recovery keys from a Samba AD DC.(CVE-2023-0614)",
    "severity": null,
    "affected": [
        {
            "package": {
                "ecosystem": "openEuler-22.03-LTS-SP1",
                "name": "libldb",
                "purl": "pkg:rpm/libldb@2.6.1-2.oe2203sp1"
            },
            "severity": null,
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "repo": "",
                    "events": [
                        {
                            "introduced": "0",
                            "fixed": "2.6.1-2.oe2203sp1",
                            "last_affected": "",
                            "limit": ""
                        }
                    ],
                    "database_specific": null
                }
            ],
            "versions": null,
            "ecosystem_specific": {
                "aarch64": [
                    "libldb-debuginfo-2.6.1-2.oe2203sp1.aarch64.rpm",
                    "libldb-debugsource-2.6.1-2.oe2203sp1.aarch64.rpm",
                    "python-ldb-devel-common-2.6.1-2.oe2203sp1.aarch64.rpm",
                    "libldb-2.6.1-2.oe2203sp1.aarch64.rpm",
                    "python3-ldb-2.6.1-2.oe2203sp1.aarch64.rpm",
                    "libldb-devel-2.6.1-2.oe2203sp1.aarch64.rpm",
                    "python3-ldb-devel-2.6.1-2.oe2203sp1.aarch64.rpm"
                ],
                "noarch": [
                    "libldb-help-2.6.1-2.oe2203sp1.noarch.rpm"
                ],
                "src": [
                    "libldb-2.6.1-2.oe2203sp1.src.rpm"
                ],
                "x86_64": [
                    "libldb-debugsource-2.6.1-2.oe2203sp1.x86_64.rpm",
                    "python-ldb-devel-common-2.6.1-2.oe2203sp1.x86_64.rpm",
                    "libldb-2.6.1-2.oe2203sp1.x86_64.rpm",
                    "python3-ldb-devel-2.6.1-2.oe2203sp1.x86_64.rpm",
                    "libldb-debuginfo-2.6.1-2.oe2203sp1.x86_64.rpm",
                    "libldb-devel-2.6.1-2.oe2203sp1.x86_64.rpm",
                    "python3-ldb-2.6.1-2.oe2203sp1.x86_64.rpm"
                ]
            },
            "database_specific": null
        }
    ],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2023-0614"
        }
    ],
    "credits": null,
    "database_specific": {
        "severity": "Medium"
    }
}