{
    "schema_version": "1.6.0",
    "id": "OESA-2022-1562",
    "modified": "2022-03-07T00:00:00Z",
    "published": "2022-03-07T00:00:00Z",
    "withdrawn": "",
    "aliases": null,
    "related": [
        "CVE-2020-29651"
    ],
    "summary": "python-py security update",
    "details": "Library with cross-python path, ini-parsing, io, code, log facilities.\r\n\r\nSecurity Fix(es):\r\n\r\nA denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.(CVE-2020-29651)",
    "severity": null,
    "affected": [
        {
            "package": {
                "ecosystem": "openEuler-20.03-LTS-SP1",
                "name": "python-py",
                "purl": "pkg:rpm/python-py@1.5.4-5.oe1"
            },
            "severity": null,
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "repo": "",
                    "events": [
                        {
                            "introduced": "0",
                            "fixed": "1.5.4-5.oe1",
                            "last_affected": "",
                            "limit": ""
                        }
                    ],
                    "database_specific": null
                }
            ],
            "versions": null,
            "ecosystem_specific": {
                "noarch": [
                    "python3-py-1.5.4-5.oe1.noarch.rpm",
                    "python-py-help-1.5.4-5.oe1.noarch.rpm",
                    "python2-py-1.5.4-5.oe1.noarch.rpm"
                ],
                "src": [
                    "python-py-1.5.4-5.oe1.src.rpm"
                ]
            },
            "database_specific": null
        },
        {
            "package": {
                "ecosystem": "openEuler-20.03-LTS-SP2",
                "name": "python-py",
                "purl": "pkg:rpm/python-py@1.5.4-5.oe1"
            },
            "severity": null,
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "repo": "",
                    "events": [
                        {
                            "introduced": "0",
                            "fixed": "1.5.4-5.oe1",
                            "last_affected": "",
                            "limit": ""
                        }
                    ],
                    "database_specific": null
                }
            ],
            "versions": null,
            "ecosystem_specific": {
                "noarch": [
                    "python3-py-1.5.4-5.oe1.noarch.rpm",
                    "python2-py-1.5.4-5.oe1.noarch.rpm",
                    "python-py-help-1.5.4-5.oe1.noarch.rpm"
                ],
                "src": [
                    "python-py-1.5.4-5.oe1.src.rpm"
                ]
            },
            "database_specific": null
        },
        {
            "package": {
                "ecosystem": "openEuler-20.03-LTS-SP3",
                "name": "python-py",
                "purl": "pkg:rpm/python-py@1.5.4-5.oe1"
            },
            "severity": null,
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "repo": "",
                    "events": [
                        {
                            "introduced": "0",
                            "fixed": "1.5.4-5.oe1",
                            "last_affected": "",
                            "limit": ""
                        }
                    ],
                    "database_specific": null
                }
            ],
            "versions": null,
            "ecosystem_specific": {
                "noarch": [
                    "python-py-help-1.5.4-5.oe1.noarch.rpm",
                    "python3-py-1.5.4-5.oe1.noarch.rpm",
                    "python2-py-1.5.4-5.oe1.noarch.rpm"
                ],
                "src": [
                    "python-py-1.5.4-5.oe1.src.rpm"
                ]
            },
            "database_specific": null
        }
    ],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-29651"
        }
    ],
    "credits": null,
    "database_specific": {
        "severity": "High"
    }
}