{
    "schema_version": "1.6.0",
    "id": "OESA-2021-1223",
    "modified": "2021-06-12T00:00:00Z",
    "published": "2021-06-12T00:00:00Z",
    "withdrawn": "",
    "aliases": null,
    "related": [
        "CVE-2021-20266",
        "CVE-2021-3421"
    ],
    "summary": "rpm security update",
    "details": "The RPM Package Manager (RPM) is a powerful package management system capability as below\r\n\r\nSecurity Fix(es):\r\n\r\nA flaw was found in RPM\u0026apos;s hdrblobInit() in lib/header.c. This flaw allows an attacker who can modify the rpmdb to cause an out-of-bounds read. The highest threat from this vulnerability is to system availability.(CVE-2021-20266)\r\n\r\nA flaw was found in the RPM package in the read functionality. This flaw allows an attacker who can convince a victim to install a seemingly verifiable package or compromise an RPM repository, to cause RPM database corruption. The highest threat from this vulnerability is to data integrity. This flaw affects RPM versions before 4.17.0-alpha.(CVE-2021-3421)",
    "severity": null,
    "affected": [
        {
            "package": {
                "ecosystem": "openEuler-20.03-LTS-SP1",
                "name": "rpm",
                "purl": "pkg:rpm/rpm@4.15.1-24.oe1"
            },
            "severity": null,
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "repo": "",
                    "events": [
                        {
                            "introduced": "0",
                            "fixed": "4.15.1-24.oe1",
                            "last_affected": "",
                            "limit": ""
                        }
                    ],
                    "database_specific": null
                }
            ],
            "versions": null,
            "ecosystem_specific": {
                "aarch64": [
                    "rpm-build-4.15.1-24.oe1.aarch64.rpm",
                    "rpm-libs-4.15.1-24.oe1.aarch64.rpm",
                    "python3-rpm-4.15.1-24.oe1.aarch64.rpm",
                    "rpm-devel-4.15.1-24.oe1.aarch64.rpm",
                    "python2-rpm-4.15.1-24.oe1.aarch64.rpm",
                    "rpm-debugsource-4.15.1-24.oe1.aarch64.rpm",
                    "rpm-debuginfo-4.15.1-24.oe1.aarch64.rpm",
                    "rpm-4.15.1-24.oe1.aarch64.rpm"
                ],
                "noarch": [
                    "rpm-help-4.15.1-24.oe1.noarch.rpm"
                ],
                "src": [
                    "rpm-4.15.1-24.oe1.src.rpm"
                ],
                "x86_64": [
                    "rpm-4.15.1-24.oe1.x86_64.rpm",
                    "rpm-debuginfo-4.15.1-24.oe1.x86_64.rpm",
                    "rpm-devel-4.15.1-24.oe1.x86_64.rpm",
                    "python3-rpm-4.15.1-24.oe1.x86_64.rpm",
                    "rpm-libs-4.15.1-24.oe1.x86_64.rpm",
                    "rpm-debugsource-4.15.1-24.oe1.x86_64.rpm",
                    "python2-rpm-4.15.1-24.oe1.x86_64.rpm",
                    "rpm-build-4.15.1-24.oe1.x86_64.rpm"
                ]
            },
            "database_specific": null
        }
    ],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-20266"
        },
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-3421"
        }
    ],
    "credits": null,
    "database_specific": {
        "severity": "Medium"
    }
}