{
    "schema_version": "1.6.0",
    "id": "OESA-2021-1224",
    "modified": "2021-06-22T00:00:00Z",
    "published": "2021-06-22T00:00:00Z",
    "withdrawn": "",
    "aliases": null,
    "related": [
        "CVE-2021-3445"
    ],
    "summary": "libdnf security update",
    "details": "A Library providing simplified C and Python API to libsolv.\r\n\r\nSecurity Fix(es):\r\n\r\nA flaw was found in libdnf\u0026apos;s signature verification functionality in versions before 0.60.1. This flaw allows an attacker to achieve code execution if they can alter the header information of an RPM package and then trick a user or system into installing it. The highest risk of this vulnerability is to confidentiality, integrity, as well as system availability.(CVE-2021-3445)",
    "severity": null,
    "affected": [
        {
            "package": {
                "ecosystem": "openEuler-20.03-LTS-SP1",
                "name": "libdnf",
                "purl": "pkg:rpm/libdnf@0.48.0-2.oe1"
            },
            "severity": null,
            "ranges": [
                {
                    "type": "ECOSYSTEM",
                    "repo": "",
                    "events": [
                        {
                            "introduced": "0",
                            "fixed": "0.48.0-2.oe1",
                            "last_affected": "",
                            "limit": ""
                        }
                    ],
                    "database_specific": null
                }
            ],
            "versions": null,
            "ecosystem_specific": {
                "aarch64": [
                    "python3-hawkey-0.48.0-2.oe1.aarch64.rpm",
                    "libdnf-devel-0.48.0-2.oe1.aarch64.rpm",
                    "python2-libdnf-0.48.0-2.oe1.aarch64.rpm",
                    "libdnf-debuginfo-0.48.0-2.oe1.aarch64.rpm",
                    "python3-libdnf-0.48.0-2.oe1.aarch64.rpm",
                    "libdnf-debugsource-0.48.0-2.oe1.aarch64.rpm",
                    "libdnf-0.48.0-2.oe1.aarch64.rpm",
                    "python2-hawkey-0.48.0-2.oe1.aarch64.rpm"
                ],
                "src": [
                    "libdnf-0.48.0-2.oe1.src.rpm"
                ],
                "x86_64": [
                    "libdnf-devel-0.48.0-2.oe1.x86_64.rpm",
                    "python2-hawkey-0.48.0-2.oe1.x86_64.rpm",
                    "python3-hawkey-0.48.0-2.oe1.x86_64.rpm",
                    "libdnf-debuginfo-0.48.0-2.oe1.x86_64.rpm",
                    "python3-libdnf-0.48.0-2.oe1.x86_64.rpm",
                    "libdnf-debugsource-0.48.0-2.oe1.x86_64.rpm",
                    "libdnf-0.48.0-2.oe1.x86_64.rpm",
                    "python2-libdnf-0.48.0-2.oe1.x86_64.rpm"
                ]
            },
            "database_specific": null
        }
    ],
    "references": [
        {
            "type": "ADVISORY",
            "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-3445"
        }
    ],
    "credits": null,
    "database_specific": {
        "severity": "High"
    }
}