{"schema_version":"1.6.0","id":"OESA-2024-1254","modified":"2024-03-08T11:32:32Z","published":"2024-03-08T11:32:32Z","related":["CVE-2024-27351"],"summary":"python-django security update","details":"Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.\r\n\r\nSecurity Fix(es):\r\n\r\nAn inefficient regular expression complexity flaw was found in the Truncator.words function and truncatewords_html filter of Django. This issue may allow an attacker to use a suitably crafted string to cause a denial of service.(CVE-2024-27351)","affected":[{"package":{"ecosystem":"openEuler-20.03-LTS-SP1","name":"python-django","purl":"pkg:rpm/openEuler/python-django&distro=openEuler-20.03-LTS-SP1"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"2.2.27-11.oe1"}]}],"ecosystem_specific":{"noarch":["python3-Django-2.2.27-11.oe1.noarch.rpm","python-django-help-2.2.27-11.oe1.noarch.rpm"],"src":["python-django-2.2.27-11.oe1.src.rpm"]}},{"package":{"ecosystem":"openEuler-20.03-LTS-SP4","name":"python-django","purl":"pkg:rpm/openEuler/python-django&distro=openEuler-20.03-LTS-SP4"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"2.2.27-11.oe2003sp4"}]}],"ecosystem_specific":{"noarch":["python3-Django-2.2.27-11.oe2003sp4.noarch.rpm","python-django-help-2.2.27-11.oe2003sp4.noarch.rpm"],"src":["python-django-2.2.27-11.oe2003sp4.src.rpm"]}},{"package":{"ecosystem":"openEuler-22.03-LTS","name":"python-django","purl":"pkg:rpm/openEuler/python-django&distro=openEuler-22.03-LTS"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"3.2.12-10.oe2203sp3"}]}],"ecosystem_specific":{"noarch":["python-django-help-2.2.27-11.oe2203.noarch.rpm","python3-Django-2.2.27-11.oe2203.noarch.rpm","python-django-help-3.2.12-10.oe2203sp1.noarch.rpm","python3-Django-3.2.12-10.oe2203sp1.noarch.rpm","python3-Django-3.2.12-10.oe2203sp2.noarch.rpm","python-django-help-3.2.12-10.oe2203sp2.noarch.rpm","python-django-help-3.2.12-10.oe2203sp3.noarch.rpm","python3-Django-3.2.12-10.oe2203sp3.noarch.rpm"],"src":["python-django-2.2.27-11.oe2203.src.rpm","python-django-3.2.12-10.oe2203sp1.src.rpm","python-django-3.2.12-10.oe2203sp2.src.rpm","python-django-3.2.12-10.oe2203sp3.src.rpm"]}},{"package":{"ecosystem":"openEuler-22.03-LTS-SP1","name":"python-django","purl":"pkg:rpm/openEuler/python-django&distro=openEuler-22.03-LTS-SP1"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"3.2.12-10.oe2203sp1"}]}],"ecosystem_specific":{"noarch":["python-django-help-3.2.12-10.oe2203sp1.noarch.rpm","python3-Django-3.2.12-10.oe2203sp1.noarch.rpm"],"src":["python-django-3.2.12-10.oe2203sp1.src.rpm"]}},{"package":{"ecosystem":"openEuler-22.03-LTS-SP2","name":"python-django","purl":"pkg:rpm/openEuler/python-django&distro=openEuler-22.03-LTS-SP2"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"3.2.12-10.oe2203sp2"}]}],"ecosystem_specific":{"noarch":["python3-Django-3.2.12-10.oe2203sp2.noarch.rpm","python-django-help-3.2.12-10.oe2203sp2.noarch.rpm"],"src":["python-django-3.2.12-10.oe2203sp2.src.rpm"]}},{"package":{"ecosystem":"openEuler-22.03-LTS-SP3","name":"python-django","purl":"pkg:rpm/openEuler/python-django&distro=openEuler-22.03-LTS-SP3"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"3.2.12-10.oe2203sp3"}]}],"ecosystem_specific":{"noarch":["python-django-help-3.2.12-10.oe2203sp3.noarch.rpm","python3-Django-3.2.12-10.oe2203sp3.noarch.rpm"],"src":["python-django-3.2.12-10.oe2203sp3.src.rpm"]}}],"references":[{"type":"ADVISORY","url":"https://www.openeuler.org/en/security/safety-bulletin/detail.html?id=openEuler-SA-2024-1254"},{"type":"ADVISORY","url":"https://nvd.nist.gov/vuln/detail/CVE-2024-27351"}],"database_specific":{"severity":"High"}}
