{"schema_version":"1.6.0","id":"OESA-2024-1974","modified":"2024-08-09T11:33:02Z","published":"2024-08-09T11:33:02Z","related":["CVE-2024-39614"],"summary":"python-django security update","details":"Django is a high-level Python Web framework that encourages rapid development and clean, pragmatic design.\r\n\r\nSecurity Fix(es):\r\n\r\nAn issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. get_supported_language_variant() was subject to a potential denial-of-service attack when used with very long strings containing specific characters.(CVE-2024-39614)","affected":[{"package":{"ecosystem":"openEuler-24.03-LTS","name":"python-django","purl":"pkg:rpm/openEuler/python-django&distro=openEuler-24.03-LTS"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"4.2.14-1.oe2403"}]}],"ecosystem_specific":{"noarch":["python-django-help-4.2.14-1.oe2403.noarch.rpm","python3-Django-4.2.14-1.oe2403.noarch.rpm"],"src":["python-django-4.2.14-1.oe2403.src.rpm"]}}],"references":[{"type":"ADVISORY","url":"https://www.openeuler.org/zh/security/security-bulletins/detail/?id=openEuler-SA-2024-1974"},{"type":"ADVISORY","url":"https://nvd.nist.gov/vuln/detail/CVE-2024-39614"}],"database_specific":{"severity":"High"}}
