{"schema_version":"1.6.0","id":"OESA-2022-1540","modified":"2022-02-26T11:31:16Z","published":"2022-02-26T11:31:16Z","related":["CVE-2022-24303"],"summary":"python-pillow security update","details":"Python image processing library.\r\n\r\nSecurity Fix(es):\r\n\r\nPillow is a PIL (Python Imaging Library) fork. Affected versions of this package are vulnerable to Improper Input Validation. When the path to the temporary directory on Linux or macOS contained a space, this would break removal of the temporary image file after im.show() (and related actions), and potentially remove an unrelated file.(CVE-2022-24303)","affected":[{"package":{"ecosystem":"openEuler-20.03-LTS-SP1","name":"python-pillow","purl":"pkg:rpm/openEuler/python-pillow&distro=openEuler-20.03-LTS-SP1"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"8.1.1-9.oe1"}]}],"ecosystem_specific":{"aarch64":["python-pillow-debugsource-8.1.1-9.oe1.aarch64.rpm","python3-pillow-devel-8.1.1-9.oe1.aarch64.rpm","python3-pillow-qt-8.1.1-9.oe1.aarch64.rpm","python-pillow-debuginfo-8.1.1-9.oe1.aarch64.rpm","python3-pillow-tk-8.1.1-9.oe1.aarch64.rpm","python3-pillow-8.1.1-9.oe1.aarch64.rpm"],"noarch":["python3-pillow-help-8.1.1-9.oe1.noarch.rpm"],"src":["python-pillow-8.1.1-9.oe1.src.rpm"],"x86_64":["python-pillow-debuginfo-8.1.1-9.oe1.x86_64.rpm","python3-pillow-tk-8.1.1-9.oe1.x86_64.rpm","python3-pillow-8.1.1-9.oe1.x86_64.rpm","python3-pillow-qt-8.1.1-9.oe1.x86_64.rpm","python-pillow-debugsource-8.1.1-9.oe1.x86_64.rpm","python3-pillow-devel-8.1.1-9.oe1.x86_64.rpm"]}},{"package":{"ecosystem":"openEuler-20.03-LTS-SP2","name":"python-pillow","purl":"pkg:rpm/openEuler/python-pillow&distro=openEuler-20.03-LTS-SP2"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"8.1.1-9.oe1"}]}],"ecosystem_specific":{"aarch64":["python3-pillow-8.1.1-9.oe1.aarch64.rpm","python-pillow-debugsource-8.1.1-9.oe1.aarch64.rpm","python3-pillow-devel-8.1.1-9.oe1.aarch64.rpm","python3-pillow-tk-8.1.1-9.oe1.aarch64.rpm","python-pillow-debuginfo-8.1.1-9.oe1.aarch64.rpm","python3-pillow-qt-8.1.1-9.oe1.aarch64.rpm"],"noarch":["python3-pillow-help-8.1.1-9.oe1.noarch.rpm"],"src":["python-pillow-8.1.1-9.oe1.src.rpm"],"x86_64":["python3-pillow-tk-8.1.1-9.oe1.x86_64.rpm","python3-pillow-devel-8.1.1-9.oe1.x86_64.rpm","python3-pillow-8.1.1-9.oe1.x86_64.rpm","python3-pillow-qt-8.1.1-9.oe1.x86_64.rpm","python-pillow-debuginfo-8.1.1-9.oe1.x86_64.rpm","python-pillow-debugsource-8.1.1-9.oe1.x86_64.rpm"]}},{"package":{"ecosystem":"openEuler-20.03-LTS-SP3","name":"python-pillow","purl":"pkg:rpm/openEuler/python-pillow&distro=openEuler-20.03-LTS-SP3"},"ranges":[{"type":"ECOSYSTEM","events":[{"introduced":"0","fixed":"8.1.1-9.oe1"}]}],"ecosystem_specific":{"aarch64":["python3-pillow-tk-8.1.1-9.oe1.aarch64.rpm","python3-pillow-8.1.1-9.oe1.aarch64.rpm","python-pillow-debuginfo-8.1.1-9.oe1.aarch64.rpm","python3-pillow-qt-8.1.1-9.oe1.aarch64.rpm","python-pillow-debugsource-8.1.1-9.oe1.aarch64.rpm","python3-pillow-devel-8.1.1-9.oe1.aarch64.rpm"],"noarch":["python3-pillow-help-8.1.1-9.oe1.noarch.rpm"],"src":["python-pillow-8.1.1-9.oe1.src.rpm"],"x86_64":["python3-pillow-8.1.1-9.oe1.x86_64.rpm","python-pillow-debugsource-8.1.1-9.oe1.x86_64.rpm","python3-pillow-devel-8.1.1-9.oe1.x86_64.rpm","python3-pillow-tk-8.1.1-9.oe1.x86_64.rpm","python-pillow-debuginfo-8.1.1-9.oe1.x86_64.rpm","python3-pillow-qt-8.1.1-9.oe1.x86_64.rpm"]}}],"references":[{"type":"ADVISORY","url":"https://www.openeuler.org/en/security/safety-bulletin/detail.html?id=openEuler-SA-2022-1540"},{"type":"ADVISORY","url":"https://nvd.nist.gov/vuln/detail/CVE-2022-24303"}],"database_specific":{"severity":"Medium"}}
